// policy_app/src/app/add-policy/add-policy.component.ts
import { Component } from '@angular/core';
import { NavbarComponent } from '../navbar/navbar.component';
import { Router } from '@angular/router';
import { ApiService } from '../services/api.service';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { ToastrService } from 'ngx-toastr';
@Component({
  selector: 'app-add-policy',
  imports: [NavbarComponent,FormsModule,CommonModule,],
  templateUrl: './add-policy.component.html',
  styleUrl: './add-policy.component.scss'
})
export class AddPolicyComponent {
  policyData = {
    policyNumber: '',
    chassisNumber: '',
    
  };
  result= '';
  errorMessage = '';
  username= '';
  submitted = false;
  constructor(private apiService : ApiService, private router: Router, private toastr : ToastrService){}
 
  onSubmit() {
      this.result= '';
      this.errorMessage = '';
  if (this.policyData.policyNumber && this.policyData.chassisNumber) {
    console.log('Form submitted:', this.policyData);
    this.submitted = true;

    this.apiService.checkPolicy(this.policyData).subscribe({
      next: (response) => {
        if (response && response.vehicle && response.policy) { 
          console.log('Policy response:', response.vehicle, response.policy);
          
          this.toastr.success('Policy and vehicle found successfully!',"Data found",{
            timeOut: 3000,
            positionClass: 'toast-top-center', 
            progressBar: true,
            closeButton: true,
            
          });
          
            this.result = `Policy and vehicle found:\n
            Vehicle Registration: ${response.vehicle.registrationNumber}
            Date of Purchase: ${response.vehicle.dateOfPurchase?.split('T')[0]}
            Ex-Showroom Price: ₹${response.vehicle.exShowroomPrice}
            Policy Effective Date: ${response.policy.policyEffectiveDate}
            Policy Expiration Date: ${response.policy.policyExpirationDate}
            Total Premium: ₹${response.policy.totalPremium}`;
         

   
        } 
        else if (response && response.message) {
          // this.errorMessage = response.message;
          this.toastr.warning(this.errorMessage,"Warning");
          
        }
        
        else {
          alert('Unexpected response from the server.');
          this.toastr.error('Unexpected response from the server.',"Error");
          console.error('Unexpected response:', response);
        }
      },
      error: (error) => {
        console.error('Error checking policy:', error);
        alert('An error occurred while checking the policy. Please try again.');
      }
    });
  } else {
    alert('Please fill in all required fields.');
  }
}

addPolicy() {
  
  this.username = localStorage.getItem('username') || '';
  console.log('Policy response:', this.policyData.policyNumber, this.username);
  this.apiService.addPolicy(this.policyData.policyNumber, this.username).subscribe({
    next: (response) => {
    if (response && response.message) {  
     if (response.message === 'Policy is added') {
          this.result = 'Policy added successfully!';
          this.errorMessage = '';
        } else if (response.message === 'Already Added') {
          this.errorMessage = 'This policy is already added to your account';
          this.result = '';
        } else {
          this.errorMessage = response.message;
          this.result = '';
        }
        console.log('Server response:', response);
      } else {
        this.errorMessage = 'Unexpected response from the server';
        console.error('Unexpected response:', response);
      }
    }
});
}



 
  

}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <title>Policy Portal</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />


</head>

<body class="bg-light min-vh-100">
  
  <app-navbar></app-navbar>

  <div class="container mt-5">
    <div class="row justify-content-center">
     
      <div class="col-md-5">
        <div class="card shadow-sm">
          <div class="card-header bg-primary text-white">
            <h5 class="mb-0"><i class="bi bi-search"></i>  Find Policy</h5>
          </div>
          <div class="card-body">
            <form class="mt-3" (ngSubmit)="onSubmit()">
              <div class="form-group mb-3">
                <label for="policyNumber" class="form-label">Policy Number</label>
                <input type="text" class="form-control" id="policyNumber" name="policyNumber"
                  placeholder="Enter policy number" [(ngModel)]="policyData.policyNumber" required />
              </div><br>
              <div class="form-group mb-3">
                <label for="chassisNumber" class="form-label">Chassis Number</label>
                <input type="text" class="form-control" id="chassisNumber" name="chassisNumber"
                  placeholder="Enter chassis number" [(ngModel)]="policyData.chassisNumber" required />
              </div>
              <div class="d-grid">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
        </div>
      </div>


      <div class="col-md-6">
        <div class="card shadow-sm mb-4" *ngIf="result">
          <div class="card-header bg-success text-white">
            <h5 class="mb-0">Results</h5>
          </div>
          <div class="card-body">
            <pre class="bg-light p-3 rounded">{{ result }}</pre>
            <div class="d-grid mt-3">
              <button class="btn btn-success" (click)="addPolicy()">
                Add this policy
              </button>
            </div>
          </div>
        </div>

        

        <div class="card border-danger mb-4" *ngIf="errorMessage">
          <div class="card-header bg-danger text-white">
            <h5 class="mb-0">Error</h5>
          </div>
          <div class="card-body">
            <div class="alert alert-danger mb-0">
              {{ errorMessage }}
            </div>
          </div>
        </div>
      </div>

    </div>
 
  </div>
</body>

</html>

// next.js/policy-portal/src/app/add_policy/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';

import { ToastContainer, toast } from 'react-toastify';
import CollapsibleSidebar from '@/components/sidebar';
import 'react-toastify/dist/ReactToastify.css';
import { findPolicy ,addPolicy} from '@/services/api';

import {formatNumberWithCommas} from '@/utils/formatNumber'; 
import {formatDate} from '@/utils/formatDate'; 

type PolicyResponse = {
  vehicle: {
    registrationNumber: string;
    dateOfPurchase: string;
    exShowroomPrice: number;
  };
  policy: {
    policyEffectiveDate: string;
    policyExpirationDate: string;
    totalPremium: number;
  };
};

export default function AddPolicyPage() {
  const router = useRouter();

  const [policyData, setPolicyData] = useState({
    policyNumber: '',
    chassisNumber: '',
  });

  const [result, setResult] = useState<PolicyResponse | null >(null);
 

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setPolicyData({ ...policyData, [e.target.name]: e.target.value });
  };

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setResult(null);
    

    if (!policyData.policyNumber || !policyData.chassisNumber) {
      toast.warning('Please fill in all required fields.');
      return;
    }

  

    try {
      const data:PolicyResponse = await findPolicy(policyData);
      setResult(data);
    } catch (error: any) {
      
      toast.error(error.message || 'Failed to find policy.');
     
    }


  };

 const add_policy = async () => {
  const username = localStorage.getItem('username');
  console.log(username);
  if (!username) {
    toast.error("Username not found. Please log in again.");
    return;
  }

  try {
    const data = await addPolicy(policyData.policyNumber, username);
   
    toast.success("Policy added successfully!");
    
  } catch (error: any) {
    toast.error(error.message || "Failed to add policy.");
  }
};


  return (<>
    <ToastContainer />
    <div className="min-h-screen bg-gray-100 p-6">
    
      <CollapsibleSidebar />


      <div className="mt-10 ml-15 mr-auto sm:ml-auto max-w-sm sm:max-w-md md:max-w-lg lg:max-w-xl bg-white p-6 sm:p-6 rounded shadow">

        <h2 className="text-xl font-bold mb-6 text-gray-800 text-center">Find Policy</h2>

        <form onSubmit={onSubmit} className="space-y-6">
          <div className="relative z-0 w-full group">
            <input
              type="text"
              name="policyNumber"
              id="policyNumber"
              value={policyData.policyNumber}
              onChange={handleChange}
              placeholder=" "
              required
              className="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent 
              border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0
               focus:border-blue-600 peer"
            />
            <label
              htmlFor="policyNumber"
              className="absolute text-sm text-gray-500 duration-300 transform scale-75 -translate-y-4 top-2.5 left-2.5 z-10 origin-[0] 
      peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-2.5 peer-focus:scale-75 
      peer-focus:-translate-y-4  peer-focus:text-blue-600"        >
              Policy Number
            </label>
          </div>
        <br></br>
          <div className="relative z-0 w-full group">
            <input
              type="text"
              name="chassisNumber"
              id="chassisNumber"
              value={policyData.chassisNumber}
              onChange={handleChange}
              placeholder=" "
              required
               className="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent 
              border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0
               focus:border-blue-600 peer"
            />
            <label
              htmlFor="policyNumber"
              className="absolute text-sm text-gray-500 duration-300 transform scale-75 -translate-y-4 top-2.5 left-2.5 z-10 origin-[0] 
      peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-2.5 peer-focus:scale-75 
      peer-focus:-translate-y-4  peer-focus:text-blue-600"        >
              Chassis Number
            </label>
          </div>

          <button
            type="submit"
            className="w-full bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-lg text-sm px-5 py-2.5 text-center"
          >
            Submit
          </button>
        </form>

        {result && result.vehicle && result.policy && (
          <div className="mt-6 p-4 border border-green-300 bg-green-50 rounded">
            <h3 className="font-semibold text-green-700 mb-2">Policy Found:</h3>
           
             <pre className="text-sm whitespace-pre-wrap text-gray-800"><strong>Registration No:</strong> {result.vehicle.registrationNumber}</pre>
            <pre className="text-sm whitespace-pre-wrap text-gray-800"><strong>Date of Purchase:</strong> {formatDate(result.vehicle.dateOfPurchase)}</pre>
            <pre className="text-sm whitespace-pre-wrap text-gray-800"><strong>Ex-Showroom Price:</strong> ₹ {formatNumberWithCommas(result.vehicle.exShowroomPrice)}</pre>
            <pre className="text-sm whitespace-pre-wrap text-gray-800"><strong>Policy Start:</strong> {formatDate(result.policy.policyEffectiveDate)}</pre>
            <pre className="text-sm whitespace-pre-wrap text-gray-800"><strong>Policy End:</strong> {formatDate(result.policy.policyExpirationDate)}</pre>
            <pre className="text-sm whitespace-pre-wrap text-gray-800"><strong>Total Premium:</strong> ₹{formatNumberWithCommas(result.policy.totalPremium)}</pre>
  
            <button
              onClick={add_policy}
              className="mt-4 bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded"
            >
              Add this policy
            </button>
          </div>
        )}
      </div>
    </div>
    </>
  );
}
